=== spawnhead/dcl-4/src/main/webapp/WEB-INF/classes/resources/dtd/xml-permissions_1_1.dtd
<?xml version='1.0' encoding='utf-8'?>

<!ENTITY % role_attrs "
  scope  (global|project)  'global'
  permission  (readonly|full)  'readonly'"
>

<!ELEMENT xml-permissions (action*)>

<!ELEMENT action ((admin | manager | declarant | economist | lawyer | user_in_lithuania | other_user_in_Minsk | staff_of_service | logistic)*)>
<!ATTLIST action name CDATA  #REQUIRED>

<!ELEMENT admin  EMPTY >

<!ELEMENT manager EMPTY >

<!ELEMENT declarant EMPTY >

<!ELEMENT economist EMPTY >

<!ELEMENT lawyer EMPTY >

<!ELEMENT user_in_lithuania EMPTY >

<!ELEMENT other_user_in_Minsk EMPTY >

<!ELEMENT staff_of_service EMPTY >

<!ELEMENT logistic EMPTY >

=== spawnhead/dcl-4/src/main/webapp/WEB-INF/classes/resources/xml-permissions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE  xml-permissions PUBLIC "xml-permissions_1_1.dtd" "dtd/xml-permissions_1_1.dtd">
<xml-permissions>

 <!--
  // т.к. проверяется совпадение первых символов (для того, чтобы работали стандартные акшн с разными диспачами),
  // нужно избегать ситуаций, когда имеем одинаковые начальные названия, но разные права
  // Пример:
  // <action name="/Menu.do?current_menu_id=id.contract"> и
  // <action name="/Menu.do?current_menu_id=id.contractors">
  // для второй строки действуют права первой.
 --> 

<!-- begin menu section -->
  <action name="/Menu.do?current_menu_id=id.personalOffice">
    <admin/>
    <economist/>
    <manager/>
    <declarant/>
    <lawyer/>
    <user_in_lithuania/>
    <other_user_in_Minsk/>
    <staff_of_service/>
    <logistic/>
  </action>
  <action name="/Menu.do?current_menu_id=id.office">
    <admin/>
    <economist/>
    <manager/>
    <declarant/>
    <lawyer/>
    <user_in_lithuania/>
    <other_user_in_Minsk/>
    <staff_of_service/>
    <logistic/>
  </action>
  <action name="/Menu.do?current_menu_id=id.personalSettings">
    <admin/>
    <economist/>
    <manager/>
    <declarant/>
    <lawyer/>
    <user_in_lithuania/>
    <other_user_in_Minsk/>
    <staff_of_service/>
    <logistic/>
  </action>
  <action name="/Menu.do?current_menu_id=id.journals">
    <admin/>
    <economist/>
    <manager/>
    <declarant/>
    <lawyer/>
    <user_in_lithuania/>
    <other_user_in_Minsk/>
    <staff_of_service/>
    <logistic/>
  </action>
  <action name="/Menu.do?current_menu_id=id.commercial_proposal">
    <admin/>
    <economist/>
    <manager/>
    <lawyer/>
  </action>
  <action name="/Menu.do?current_menu_id=id.condition_for_contract">
    <admin/>
    <economist/>
    <manager/>
    <lawyer/>
  </action>
  <action name="/Menu.do?current_menu_id=id.contractDoc">
    <admin/>
    <economist/>
    <manager/>
    <lawyer/>
    <user_in_lithuania/>
	  <logistic/>
  </action>
  <action name="/Menu.do?current_menu_id=id.order">
    <admin/>
    <economist/>
    <manager/>
    <user_in_lithuania/>
    <logistic/>
  </action>
  <action name="/Menu.do?current_menu_id=id.in_delivery_request">
    <admin/>
    <economist/>
    <manager/>
    <declarant/>
  </action>
  <action name="/Menu.do?current_menu_id=id.out_delivery_request">
    <admin/>
    <economist/>
    <manager/>
    <declarant/>
  </action>
  <action name="/Menu.do?current_menu_id=id.assemble">
    <admin/>
    <economist/>
    <manager/>
    <declarant/>
  </action>
  <action name="/Menu.do?current_menu_id=id.specification_import">
    <admin/>
    <economist/>
    <declarant/>
    <manager/>
  </action>
  <action name="/Menu.do?current_menu_id=id.produce_cost">
    <admin/>
    <economist/>
    <declarant/>
  </action>
  <action name="/Menu.do?current_menu_id=id.payment">
    <admin/>
    <economist/>
    <manager/>
	  <lawyer/>
  </action>
  <action name="/Menu.do?current_menu_id=id.shipping">
    <admin/>
    <economist/>
    <manager/>
    <lawyer/>
  </action>
  <action name="/Menu.do?current_menu_id=id.cclosed">
    <admin/>
    <economist/>
  </action>
  <action name="/Menu.do?current_menu_id=id.requestContractor">
    <admin/>
    <economist/>
    <staff_of_service/>
    <manager/>
  </action>
  <action name="/Menu.do?current_menu_id=id.timeboard">
    <admin/>
    <economist/>
    <staff_of_service/>
  </action>
  <action name="/Menu.do?current_menu_id=id.current_works">
    <admin/>
    <economist/>
    <staff_of_service/>
  </action>
  <action name="/Menu.do?current_menu_id=id.woodwork_work_files">
    <admin/>
    <economist/>
    <staff_of_service/>
  </action>
  <action name="/Menu.do?current_menu_id=id.outgoingLetter">
    <admin/>
    <economist/>
    <manager/>
    <declarant/>
    <lawyer/>
    <other_user_in_Minsk/>
    <logistic/>
  </action>

  <action name="/Menu.do?current_menu_id=id.references">
    <admin/>
    <economist/>
    <manager/>
    <declarant/>
    <lawyer/>
    <other_user_in_Minsk/>
    <user_in_lithuania/>
    <logistic/>
  </action>
  <action name="/Menu.do?current_menu_id=id.contractors">
    <admin/>
    <economist/>
    <manager/>
    <lawyer/>
    <declarant/>
    <other_user_in_Minsk/>
    <logistic/>
  </action>
  <action name="/Menu.do?current_menu_id=id.nomenclature">
    <admin/>
    <economist/>
    <manager/>
    <lawyer/>
    <declarant/>
    <user_in_lithuania/>
    <logistic/>
  </action>
  <action name="/Menu.do?current_menu_id=id.custom_code">
    <admin/>
    <economist/>
    <manager/>
    <declarant/>
  </action>
  <action name="/Menu.do?current_menu_id=id.currencies">
    <admin/>
    <economist/>
    <manager/>
  </action>
  <action name="/Menu.do?current_menu_id=id.stuff_categories">
    <admin/>
    <economist/>
    <manager/>
  </action>
  <action name="/Menu.do?current_menu_id=id.montage_adjustment">
    <admin/>
    <economist/>
    <manager/>
    <user_in_lithuania/>
  </action>
  <action name="/Menu.do?current_menu_id=id.units">
    <admin/>
    <economist/>
    <manager/>
    <declarant/>
  </action>
  <action name="/Menu.do?current_menu_id=id.purposes">
    <admin/>
    <economist/>
  </action>
  <action name="/Menu.do?current_menu_id=id.doc_types_shipping">
    <admin/>
    <economist/>
    <manager/>
    <declarant/>
    <logistic/>
  </action>
  <action name="/Menu.do?current_menu_id=id.countries">
    <admin/>
    <economist/>
    <manager/>
    <declarant/>
    <lawyer/>
    <other_user_in_Minsk/>
  </action>


  <action name="/Menu.do?current_menu_id=id.reports">
    <admin/>
    <economist/>
    <manager/>
    <lawyer/>
    <declarant/>
    <user_in_lithuania/>
    <logistic/>
  </action>
  <action name="/Menu.do?current_menu_id=id.margin">
    <admin/>
    <economist/>
    <manager/>
  </action>
  <action name="/Menu.do?current_menu_id=id.goods_rest,/Menu.do?current_menu_id=id.minsk_goods_rest">
    <admin/>
    <economist/>
    <manager/>
    <declarant/>
  </action>
  <action name="/Menu.do?current_menu_id=id.lithuania_goods_rest">
    <admin/>
    <economist/>
    <manager/>
    <logistic/>
  </action>
  <action name="/Menu.do?current_menu_id=id.lithuania_goods_circulation">
    <admin/>
    <economist/>
    <manager/>
    <logistic/>
  </action>
  <action name="/Menu.do?current_menu_id=id.calculation_state">
    <admin/>
    <economist/>
    <manager/>
    <lawyer/>
    <user_in_lithuania/>
  </action>
  <action name="/Menu.do?current_menu_id=id.logistics_order">
    <admin/>
    <economist/>
    <user_in_lithuania/>
    <logistic/>
  </action>
  <action name="/Menu.do?current_menu_id=id.statistics_orders">
    <admin/>
    <economist/>
    <manager/>
    <user_in_lithuania/>
  </action>
  <action name="/Menu.do?current_menu_id=id.unexecuted_orders">
    <admin/>
    <economist/>
    <user_in_lithuania/>
    <logistic/>
  </action>
  <action name="/Menu.do?current_menu_id=id.rep_shipping">
    <admin/>
    <economist/>
    <manager/>
  </action>
  <action name="/Menu.do?current_menu_id=id.goods_circulation">
    <admin/>
    <economist/>
    <manager/>
  </action>
  <action name="/Menu.do?current_menu_id=id.prdCostReport">
    <admin/>
    <economist/>
    <user_in_lithuania/>
  </action>


  <action name="/Menu.do?current_menu_id=id.adm_zone">
    <admin/>
  </action>
  <action name="/Menu.do?current_menu_id=id.test_new_grid">
    <admin/>
  </action>
  <action name="/Menu.do?current_menu_id=id.dev_margin">
    <admin/>
  </action>
  <action name="/Menu.do?current_menu_id=id.users">
    <admin/>
  </action>
  <action name="/Menu.do?current_menu_id=id.roles">
    <admin/>
  </action>
  <action name="/Menu.do?current_menu_id=id.departments">
    <admin/>
  </action>
  <action name="/Menu.do?current_menu_id=id.languages">
    <admin/>
  </action>
  <action name="/Menu.do?current_menu_id=id.routes">
    <admin/>
  </action>
  <action name="/Menu.do?current_menu_id=id.sellers">
    <admin/>
  </action>
  <action name="/Menu.do?current_menu_id=id.blanks">
    <admin/>
  </action>
  <action name="/Menu.do?current_menu_id=id.settings">
    <admin/>
  </action>
  <action name="/Menu.do?current_menu_id=id.actions">
    <admin/>
  </action>
  <action name="/Menu.do?current_menu_id=id.log">
    <admin/>
  </action>
  <action name="/Menu.do?current_menu_id=id.filesPaths">
    <admin/>
  </action>

<!-- end menu section -->

<!-- справочник Пользователи редактирование -->
  <action name="/UsersAction.do,/UserAction.do">
    <admin/>
    <economist/>
  </action>
  <action name="/RolesAction.do,/RoleAction.do,/UserRolesAction.do">
    <admin/>
    <economist/>
  </action>
  <action name="/ContractorAction.do?dispatch=delete">
    <admin/>
  </action>
  <action name="/ContactPersonAction.do?dispatch=deleteRowFromUserGrid">
    <admin/>
  </action>
  <action name="/ContractorsAction.do,/ContractorAction.do,
                /ContractorEditActionConditionForContract.do,
                /ContractorEditActionCalculationState.do,
                /ContractorAddAction.do,
                /ContractorAddActionConditionForContract.do,
                /ContractorAddActionContract.do,
                /ContractorAddActionContractCalculationState.do,
                /ContractorAddActionOrder.do,
                /ContractorAddActionShipping.do,
                /ContractorAddActionPayment.do,
                /ContractorAddActionContractorRequest.do,
                /ContractorAddActionOutgoingLetter.do,
                /ContractorAddActionShippingCalculationState.do,
                /ContactPersonsAction.do,/ContactPersonAction.do,
                /ContactPersonEditActionConditionForContract.do,
                /ContactPersonAddAction.do,
                /ContactPersonAddActionConditionForContract.do,
                /ContactPersonAddActionOrder.do,
                /ContactPersonAddActionContractorRequest.do,
                /ContactPersonAddActionOutgoingLetter.do">
    <admin/>
    <economist/>
    <manager/>
    <lawyer/>
